#!/usr/bin/env bash

echo "Preparing the awesome..."

echo -n "Installing required node packages... "
npm install -g grunt-cli &> /dev/null
npm install &> /dev/null
echo "Done."

echo -n "Installing javascript dependencies... "
bower install --silent
echo "Done."

echo -n "Installing unit testing environment... "
cd test/
bower install --silent
cd ..

echo -n "Installing feature testing environment... "
bundle install --path vendor/gems --binstubs

echo "Done."
